version: "3"

services:
  web:
    build: .
    depends_on:
      - mariadb
    restart: 'always'
    ports:
      - '8080:80'
    links:
      - mariadb
    volumes:
      - "./src:/var/www/html"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public


  mariadb:
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    volumes: 
      - "${MYSQL_DATA_DIR}:/var/lib/mysql/"
        #      - /var/docker/mariadb/conf:/etc/mysql Use only if you know what your doing ;-)
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
